In [14]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
sent1 = "It was a beautiful rainy day that made my day awesome."
sent2 = "We made it awesome by adding more flavors in it."

In [16]:
tfidf = TfidfVectorizer()

In [17]:
new = tfidf.fit_transform([sent1, sent2])

In [18]:
df = pd.DataFrame(new.toarray(), columns=tfidf.get_feature_names_out())
df

,adding,awesome,beautiful,by,day,flavors,in,it,made,more,my,rainy,that,was,we
0,0.000000,0.219381,0.308332,0.000000,0.616664,0.000000,0.000000,0.219381,0.219381,0.000000,0.308332,0.308332,0.308332,0.308332,0.000000
1,0.332642,0.236677,0.000000,0.332642,0.000000,0.332642,0.332642,0.473355,0.236677,0.332642,0.000000,0.000000,0.000000,0.000000,0.332642

### Read the file - mreviews.txt, remove the stopwords and create tf*idf vectorize result

In [19]:
import os

In [20]:
file_path = os.path.join("datasets", "mreviews.txt")
with open(file_path, "r", encoding="utf-8") as file:
    lines = [line.strip() for line in file if line.strip()]

In [21]:
tfidf = TfidfVectorizer(stop_words='english')

In [22]:
tfidf_matrix = tfidf.fit_transform(lines)

In [24]:
df_result = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())
df_result

,absolute,adding,allowing,audience,authenticity,balancing,best,big,brightly,brilliantly,...,thought,tight,timed,triumphant,turns,twists,visually,weaves,written,year
0,0.377964,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.324869,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.324869,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.338302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.324869,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.316228,0.316228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.308973,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.308973,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.320461,...,0.320461,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.320461,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.333333,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.301511,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.301511,0.000000,0.000000,0.000000,0.000000,0.000000,0.301511,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.316228,0.000000,0.000000,0.000000,0.000000,0.000000

### TF*IDF Vectorizer by Reading File

In [29]:
f = open('datasets/mreviews.txt')
lines = f.readlines()

In [30]:
tfidf = TfidfVectorizer(stop_words='english')

In [31]:
new = tfidf.fit_transform(lines)

In [32]:
df = pd.DataFrame(new.toarray(), columns=tfidf.get_feature_names_out())
df

,absolute,adding,allowing,audience,authenticity,balancing,best,big,brightly,brilliantly,...,thought,tight,timed,triumphant,turns,twists,visually,weaves,written,year
0,0.377964,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.324869,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.324869,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.338302,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.324869,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.316228,0.316228,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.308973,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.308973,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.320461,...,0.320461,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.320461,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.333333,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.301511,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.301511,0.000000,0.000000,0.000000,0.000000,0.000000,0.301511,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.316228,0.000000,0.000000,0.000000,0.000000,0.000000